name: build
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            toolchain: vc2022,
            toolversion: vs170,
            packagelabel: oncrpc-msvc-vs170
          }
        - {
           name: "Windows Latest MinGW64",
           os: windows-latest,
           toolchain: mingw64,
           toolversion: mingw64,
           packagelabel: oncrpc-mingw64
          }
        - {
           name: "Windows Latest OWC",
           os: windows-latest,
           toolchain: owc20,
           toolversion: owc20,
           packagelabel: oncrpc-owc20
          }
        - {
           name: "Windows Legacy OWC",
           os: windows-latest,
           toolchain: owc19,
           toolversion: owc19,
           packagelabel: oncrpc-owc19
          }

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive

    - name: Setup
      if: startsWith(matrix.config.name, 'Windows')
      shell: cmd
      run: |
        c:\msys64\usr\bin\pacman --noconfirm -S zip

    - name: MSVC setup
      uses: ilammy/msvc-dev-cmd@v1
      if: startsWith(matrix.config.name, 'Windows Latest MSVC')
      with:
        arch: x86

    - name: MinGW64 setup
      if: startsWith(matrix.config.name, 'Windows Latest MinGW')
      shell: cmd
      run: |
        c:\msys64\usr\bin\pacman --noconfirm -S base-devel
        c:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-gcc
        c:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-gettext-tools
        c:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-i686-gcc
        c:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-i686-gettext-tools
        dir c:\msys64\usr\bin

    - name: OpenWatcom setup
      uses: open-watcom/setup-watcom@v0
      if: startsWith(matrix.config.name, 'Windows Latest OWC')
      with:
        version: "2.0"
        location: "C:\\Watcom"
        
    - name: OpenWatcom legacy setup
      uses: open-watcom/setup-watcom@v0
      if: startsWith(matrix.config.name, 'Windows Legacy OWC')
      with:
        version: "1.9"
        location: "C:\\Watcom"

    - name: Generate
      if: startsWith(matrix.config.name, 'Windows')
      shell: cmd
      run: |
        @if "${{ matrix.config.toolchain }}"=="mingw32" set PATH=c:\msys64\mingw32\bin;%PATH%
        @if "${{ matrix.config.toolchain }}"=="mingw64" set PATH=c:\msys64\mingw64\bin;%PATH%
        @if "${{ matrix.config.toolchain }}"=="owc20"   call .\support\owc20setenv.bat C:\Watcom
        @if "${{ matrix.config.toolchain }}"=="owc19"   call .\support\owc19setenv.bat C:\Watcom
        @set BUSYBOX=./win32/busybox
        @set PERL=c:/Strawberry/perl/bin/perl
        %PERL% makelib.pl --perlpath=c:/Strawberry/perl/bin --busybox=%BUSYBOX% "${{ matrix.config.toolchain }}"

    - name: Compile
      if: startsWith(matrix.config.name, 'Windows')
      shell: cmd
      run: |
        @if "${{ matrix.config.toolchain }}"=="mingw32" set PATH=c:\msys64\mingw32\bin;%PATH%
        @if "${{ matrix.config.toolchain }}"=="mingw64" set PATH=c:\msys64\mingw64\bin;%PATH%
        @if "${{ matrix.config.toolchain }}"=="owc20"   call .\support\owc20setenv.bat C:\Watcom
        @if "${{ matrix.config.toolchain }}"=="owc20"   set PATH=%PATH%;c:\msys64\mingw64\bin
        @if "${{ matrix.config.toolchain }}"=="owc19"   call .\support\owc19setenv.bat C:\Watcom
        @if "${{ matrix.config.toolchain }}"=="owc19"   set PATH=%PATH%;c:\msys64\mingw64\bin
        @if "${{ matrix.config.toolchain }}"=="vc2022"  set PATH=%PATH%;c:\msys64\mingw64\bin
        @set BUSYBOX=./win32/busybox
        @set PERL=c:/Strawberry/perl/bin/perl
        .\win32\gmake-42 release
        c:\msys64\usr\bin\zip ${{ matrix.config.packagelabel }}-${{ github.run_number }}.zip ^
                ./bin.${{ matrix.config.toolversion }}/release/rpc*.exe ^
                ./bin.${{ matrix.config.toolversion }}/release/*.dll ^
                ./lib.${{ matrix.config.toolversion }}/release/*.lib ^
                ./include/rpc/* ^
                ./include/*

    - name: Package
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.config.toolchain }}
        path: ./bin.${{ matrix.config.toolversion }}/release/*

    - name: Release artifacts
      if: startsWith(matrix.config.name, 'Windows')
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.config.packagelabel }}-${{ github.run_number }}.zip
        draft: true

