name: build
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            toolchain: vc2022,
            toolversion: vc170
          }
        - {
           name: "Windows Latest MinGW",
           os: windows-latest,
           toolchain: mingw64,
           toolversion: mingw64
          }
          
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive

    - uses: ilammy/msvc-dev-cmd@v1
      if: startsWith(matrix.config.name, 'Windows Latest MSVC')
      with:
        arch: x86

    - name: Generating Makefiles
      shell: cmd
      run: |
        if "${{ matrix.config.toolchain }}"=="mingw64" set PATH=d:\msys64\mingw64\bin;%PATH%
        @set PERL=c:/Strawberry/perl/bin/perl
        c:/Strawberry/perl/bin/perl makelib.pl --perlpath=c:/Strawberry/perl/bin --busybox=./win32/busybox --wget=./win32/wget "${{ matrix.config.toolchain }}"

    - name: Compiling
      shell: cmd
      run: |
        if "${{ matrix.config.toolchain }}"=="mingw64" set PATH=d:\msys64\mingw64\bin;%PATH%
        @set PERL=c:/Strawberry/perl/bin/perl
        .\win32\gmake-42 release

    - name: Package
      uses: actions/upload-artifact@v2
      with:
        name: package-"${{ matrix.config.toolchain }}"
        path: ./bin."${{ matrix.config.toolversion }}"/release/*
